In [ ]:
! pip install git+https://github.com/huggingface/transformers evaluate jiwer -q

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 22.7 MB/s eta 0:00:00
  Building wheel for transformers (pyproject.toml) ... done

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#!unzip /content/drive/MyDrive/FYP/Pakistani_English_Scripted_Speech_Corpus_Daily_Use_Sentence.zip -d /content/drive/MyDrive/FYP

Archive:  /content/drive/MyDrive/FYP/Pakistani_English_Scripted_Speech_Corpus_Daily_Use_Sentence.zip
  inflating: /content/drive/MyDrive/FYP/README.txt
  inflating: /content/drive/MyDrive/FYP/SPKINFO.txt
  inflating: /content/drive/MyDrive/FYP/UTTERANCEINFO.txt
   creating: /content/drive/MyDrive/FYP/WAV/
   creating: /content/drive/MyDrive/FYP/WAV/G0001/
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0101.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0102.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0103.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0104.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0105.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0106.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0107.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0108.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0109.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0110.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0111.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0112.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0113.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0114.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0115.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0116.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0117.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0118.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0119.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0120.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0121.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0122.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0123.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0124.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0125.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0126.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0127.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0128.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0129.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0130.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0131.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0132.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0133.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0134.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0135.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0136.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0137.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0138.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0139.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0140.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0141.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0142.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0143.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0144.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0145.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0146.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0147.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0148.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0149.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0150.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0151.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0152.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0153.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0154.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0155.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0156.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0157.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0158.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0159.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0160.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0161.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0162.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0163.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0164.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0165.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0166.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0167.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0168.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0169.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0170.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0171.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0172.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0173.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0174.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0175.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0176.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0177.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0178.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0179.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0180.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0181.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0182.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0183.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0184.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0185.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0186.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0187.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0188.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0189.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0190.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0191.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0192.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0193.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0194.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0195.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0196.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0197.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0198.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0199.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0200.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0201.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0202.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0203.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0204.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0205.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0206.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0207.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0208.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0209.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0210.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0211.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0212.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0213.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0214.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0215.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0216.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0217.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0218.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0219.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0220.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0221.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0222.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0223.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0225.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0226.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0227.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0228.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0229.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0230.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0231.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0232.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0233.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0234.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0235.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0236.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0237.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0238.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0239.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0240.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0241.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0242.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0243.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0244.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0245.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0246.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0247.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0248.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0249.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0250.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0251.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0252.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0253.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0254.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0255.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0256.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0257.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0258.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0259.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0260.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0261.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0262.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0263.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0264.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0265.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0266.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0267.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0268.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0269.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0270.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0271.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0272.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0273.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0274.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0275.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0276.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0277.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0278.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0279.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0280.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0281.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0282.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0283.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0284.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0285.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0286.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0287.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0288.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0289.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0290.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0291.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0292.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0293.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0294.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0295.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0296.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0297.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0298.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0299.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0300.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0301.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0302.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0303.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0304.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0305.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0306.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0307.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0308.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0309.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0310.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0311.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0312.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0313.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0314.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0315.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0316.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0317.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0318.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0319.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0320.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0321.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0322.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0323.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0324.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0325.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0326.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0327.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0328.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0329.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0330.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0331.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0332.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0333.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0334.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0335.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0336.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0337.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0338.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0339.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0340.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0341.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0342.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0343.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0344.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0345.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0346.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0347.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0348.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0349.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0350.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0351.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0352.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0353.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0354.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0355.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0356.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0357.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0358.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0359.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0360.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0361.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0362.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0363.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0364.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0365.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0366.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0367.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0368.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0369.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0370.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0371.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0372.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0373.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0374.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0375.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0376.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0377.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0378.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0379.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0380.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0381.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0382.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0383.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0384.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0385.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0386.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0387.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0388.wav
  inflating: /content/drive/MyDrive/FYP/WAV/G0001/G0001_0_S0389.wav

In [ ]:
import os
import time
import re
import pandas as pd
import csv
from evaluate import load
from transformers import pipeline
from transformers.models.whisper.english_normalizer import BasicTextNormalizer

In [ ]:
# Define the path to the main directory containing the subfolders
main_directory = "/content/drive/MyDrive/FYP-Language_learning/pakistani_english_dataset/WAV"

# List all subfolders inside the main directory
subfolders = [f.path for f in os.scandir(main_directory) if f.is_dir()]

# Initialize a list to store the full paths of .wav files
wav_files = []

# Loop over each subfolder
for subfolder in subfolders:
    # Get the list of all files in the current subfolder
    wav_files_in_subfolder = [os.path.join(subfolder, file) for file in os.listdir(subfolder) if file.endswith('.wav')]

    wav_files.extend(wav_files_in_subfolder[:10])

In [ ]:
print("Length of sample data : ", len(wav_files))

Length of sample data :  140

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/FYP-Language_learning/pakistani_english_dataset/UTTERANCEINFO.txt", delimiter='\t')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2191 entries, 0 to 2190
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CHANNEL        2191 non-null   object
 1   UTTRANS_ID     2191 non-null   object
 2   SPEAKER_ID     2191 non-null   object
 3   PROMPT         2191 non-null   object
 4   TRANSCRIPTION  2191 non-null   object
dtypes: object(5)
memory usage: 85.7+ KB

In [ ]:
data = data[["UTTRANS_ID", "TRANSCRIPTION"]]

In [ ]:
orignal_transcriptions = {}

# Loop through each .wav file and get the corresponding transcription from the DataFrame
for wav_path in wav_files:
  wav_id = os.path.basename(wav_path)
  transcription = data.loc[data['UTTRANS_ID'] == wav_id, 'TRANSCRIPTION'].iloc[0]
  orignal_transcriptions[wav_id] = transcription

# **Whisper distil large v3**

In [ ]:
# Use a pipeline as a high-level helper
pipe = pipeline("automatic-speech-recognition", model="distil-whisper/distil-large-v3")

Device set to use cpu

In [ ]:
def transcribe_speech(filepath):
    output = pipe(
        filepath,
        max_new_tokens=256,
        generate_kwargs={
             "task": "transcribe"
        #     "language": "english",
        },
        chunk_length_s=30,
        batch_size=8,
    )
    return output["text"]

In [ ]:
# Start the timer
start_time = time.time()

# Initialize dictionary to store the predicted transcriptions
predicted_transcriptions = {}

# Loop over each .wav file in wav_files
for wav_file in wav_files:
    # Call the transcribe function to get the transcription for each wav file
    transcription = transcribe_speech(wav_file)

    # Get the file name (ID) from the full path
    wav_id = os.path.basename(wav_file)

    # Store the transcription in the dictionary
    predicted_transcriptions[wav_id] = transcription

# Stop the timer after processing all files
end_time = time.time()

/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

KeyboardInterrupt:

In [ ]:
# Calculate total time taken in seconds
total_time = end_time - start_time

# Print the total time taken
print(f"Total time taken for transcription: {total_time:.2f} seconds")
# 1 hour 35 minute to transcribe 109 audios

In [ ]:
len(predicted_transcriptions)

108

In [ ]:
# Output CSV file path
output_csv_file = '/content/drive/MyDrive/FYP/transcriptions_comparison.csv'

# Open the CSV file for writing
with open(output_csv_file, mode='w', newline='') as file:
    writer = csv.writer(file)

    # Write header row
    writer.writerow(['id', 'original_transcription', 'predicted_transcription'])

    # Iterate over the ids in the original transcription dictionary
    for id, original in predicted_transcriptions.items():
        # Get the predicted transcription using the id
        predicted = orignal_transcriptions.get(id)

        # Write the row for the current id, original transcription, and predicted transcription
        writer.writerow([id, original, predicted])

print(f"CSV file '{output_csv_file}' has been created successfully.")

CSV file '/content/drive/MyDrive/FYP/transcriptions_comparison.csv' has been created successfully.

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/FYP/transcriptions_comparison.csv')
df['predicted_transcription'] = df['predicted_transcription'].str.strip()

In [ ]:
normalizer = BasicTextNormalizer()

df['normalized_transcription'] = df['predicted_transcription'].apply(normalizer).str.strip()

In [ ]:
wer_metric = load("wer")

wer_ortho = 100 * wer_metric.compute(
    references=df['original_transcription'], predictions=df['normalized_transcription'])

wer_ortho

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Downloading builder script:   0%|          | 0.00/4.49k [00:00<?, ?B/s]

46.09826589595375

In [ ]:
# Initialize the WER metric
wer_metric = load("wer")

# Function to check if a transcription contains digits
def contains_digits(text):
    # Return True if the text contains any digits
    return bool(re.search(r'\d', text))

# Step 1: Filter out rows where 'normalized_transcription' contains any digits
df_cleaned = df[~df['normalized_transcription'].apply(contains_digits)]

# Step 2: Calculate WER on the cleaned data
wer_ortho = 100 * wer_metric.compute(
    references=df_cleaned['original_transcription'], predictions=df_cleaned['normalized_transcription'])

print(f"Word Error Rate (WER): {wer_ortho}%")

Word Error Rate (WER): 13.136094674556212%

In [ ]:
df[['normalized_transcription', 'original_transcription']].iloc[60:80,:]

,normalized_transcription,original_transcription
60,i was just wondering if you happen to know any...,i was just wondering if you happen to know any...
61,it is a day to help the needy,it is a day to help the needy
62,675508 8 8104 671463,six seven five zero five one zero eight eight ...
63,51230736840304304 6702,five one two three zero seven three six eight ...
64,and trash say bad things about your opponent,and try say bad things about your opponent
65,3875662260 2 6033 088451,three eight seven five six six two two six zer...
66,5782370718804 825,five seven eight two three six seven zero seve...
67,768402 6268134 7831,seven six eight four zero two six two six eigh...
68,wow i just ordered from amazon is this to be e...,wow i just ordered from amzon is this to be ex...
69,think about what you are going to see and be y...,think about what you're going to say add we ar...
70,57436 087274748656031,five seven four three six zero eight seven two...
71,2107 2185361282 8 86 1538,two one zero seven two one eight five three si...
72,i like that it is somewhat based on real life ...,i liked that it is somewhat based on real life...
73,1567 3402 556 877101,one five six seven three four zero two five fi...
74,bright star about two times more massive than ...,bright star about two times more massive than ...
75,the price of cobalt has more than doubled,the price of cobalt has more than doubled
76,i remember the first time i saw star wars it b...,i remember the first time i saw star wars it b...
77,023863 4684755 847 5187 20,zero two three eight six three four six eight ...
78,5 4 2 3 6 7 286 1 57 323181811,five four two three six seven two eight six on...
79,thanked america for one of his favorite songs,thanked america for one of his favorite songs

# **Wav2vec2**

In [ ]:
from transformers import pipeline

pipe = pipeline("automatic-speech-recognition", model="facebook/wav2vec2-base-100h")

config.json:   0%|          | 0.00/1.43k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/378M [00:00<?, ?B/s]

Some weights of the model checkpoint at facebook/wav2vec2-base-100h were not used when initializing Wav2Vec2ForCTC: ['wav2vec2.mask_time_emb_vector']
- This IS expected if you are initializing Wav2Vec2ForCTC from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Wav2Vec2ForCTC from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-100h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

tokenizer_config.json:   0%|          | 0.00/376 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/358 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/96.0 [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/159 [00:00<?, ?B/s]

In [ ]:
# Start the timer
start_time = time.time()

# Initialize dictionary to store the predicted transcriptions
predicted_transcriptions = {}

# Loop over each .wav file in wav_files
for wav_file in wav_files:
    transcription = pipe(wav_file)

    # Get the file name (ID) from the full path
    wav_id = os.path.basename(wav_file)

    # Store the transcription in the dictionary
    predicted_transcriptions[wav_id] = transcription

# Stop the timer after processing all files
end_time = time.time()

In [ ]:
predicted_transcriptions

{'G0007_0_S0020.wav': {'text': 'GIVE UP STEPS THAT HINDER NORMAR DEVELOPMENT IN RELATIONS'},
 'G0007_0_S0023.wav': {'text': "THE GARDS SOLER BANNA TR YEAR'S ELECTRICITY FROM SOM LIGHT"},
 'G0007_0_S0031.wav': {'text': 'TA RUBELL ROS ALVAS BURSTLY THE KING OF ROKINROD'},
 'G0007_0_S0005.wav': {'text': 'SEVON FOUR SEVON SIX FIVE THREE SIX DEO FOR THREE THREE ZARO TWO SIX ONE SEVON EIGHTH ONE'},
 'G0007_0_S0006.wav': {'text': 'FOUR SAON SIX EIGHTH TO ONE EIGTH LIDO DU FIVE DU THEOR THREE SIX FIVE TEE O FOUR FOUR SIX'},
 'G0007_0_S0024.wav': {'text': 'AND IC TODI OF CHEF JOSEPH OF THA NESBERSS INDIANS'},
 'G0007_0_S0040.wav': {'text': 'HANGS FOR PLAYING ALONE I JUST HAVE TO SIT FOR A WINE'},
 'G0007_0_S0043.wav': {'text': 'MONE PESSENGER DIED AFTER BEING BARSHLY OUT OF THE PLAIN'},
 'G0007_0_S0018.wav': {'text': 'NO NO I HAVE TO GO NOW I HAVE TO SEE THE PHROZEN JARS NOW TO NIGHT'},
 'G0007_0_S0042.wav': {'text': 'AND SHE TANKED E FRANCH PEAPER FOR SHIRING HIGH DESPAIR'},
 'G0007_0_S0013.wav': {'text': 'I LAUGHED SO HARD SO YOU MADE ME COKE ON THE FORT I AM ATING'},
 'G0007_0_S0027.wav': {'text': 'I AM A FRESH GRAT WITH NO RELIGID EXPERIENCE SO YES ILO'},
 'G0007_0_S0025.wav': {'text': 'THE GIRL IS FOR PEOPLE ITO CAT TO KNO EACH'},
 'G0007_0_S0037.wav': {'text': 'I HIGHLY DOUBT IT I WOULD THINK THAT THEY ARE ALL JUST ON A NORMON SETERAC'},
 'G0007_0_S0004.wav': {'text': 'ONE ZERO FIVE EIGHTH FOUR SALMON SEERO THREE SEVEN SIX TWO FOUR ONE TO FIVE TO EIGHTH ONE'},
 'G0007_0_S0033.wav': {'text': 'NO IT IS HARD EVERY YEAR IN GRANT PRANK IN CHICAGO'},
 'G0007_0_S0003.wav': {'text': 'THREE DO VIZERO FOUR EIGHTH SEVEN FIVE ZEDO DO FOUR SIX DO THREE SEVON EIGHTH FIVE FOR THREE'},
 'G0007_0_S0007.wav': {'text': 'EIGHT EIGHT SEVEN FOUR SEVONE ONE ZEADLE THREE ONE TWO TWO FOUR FOUR SAVONZEADLE SIX FIVE SIX'},
 'G0007_0_S0022.wav': {'text': 'YUP I HAMVERED LISTEN TOO MUCH OF HIM BUT SO FAR I SUPPOSE IX OCE'},
 'G0007_0_S0038.wav': {'text': 'NO BUT I HAVE HEARD OFF IT IS IT GOOD'},
 'G0008_0_S0024.wav': {'text': 'ARIGHT NOW WE NOW HAVE TELL STUDENTS STUPOR DO YOU'},
 'G0008_0_S0049.wav': {'text': 'WHO DO YOU THINK THE WOOLDS AND THE MEVERICKS WILL TAKE'},
 'G0008_0_S0047.wav': {'text': "ANDNO IT'S NOT AS IF ANY OF HER RAIDY EARLISTOV WAS LESS PROVOCATIVE"},
 'G0008_0_S0016.wav': {'text': 'SHE LOOKED DOWN HER NOSE AT ME AND SNEERED'},
 'G0008_0_S0043.wav': {'text': "YES THAT'S IT I LAG DHAT ONE WHAT ABOUT BENNY GOODMEN YE MENSIONED EARLIER"},
 'G0008_0_S0025.wav': {'text': 'IDE KNOW IT WAS AN IMPULC ME RERING MY GOOD SHOOS'},
 'G0008_0_S0023.wav': {'text': "NOCK'S ERIES NOCKS I AM GLAD HEU CARD"},
 'G0008_0_S0017.wav': {'text': "WELL WE ARE STARVING WHY DON'T WE ALL GO TO GET SOMETHING TO EAT"},
 'G0008_0_S0028.wav': {'text': 'ART THE RECOMMENDATION OF THEIR DOCTRIRES ARE ON THERE ON'},
 'G0008_0_S0048.wav': {'text': 'I LIKE EVERY SINSE EQUALLY THEY ARE ALL GREAT'},
 'G0008_0_S0037.wav': {'text': 'I RALY DOUBT THEY GIN LIFT MOUNTANES WITHOUT MURDTABLE PEOPLE HAVING TO DO IT'},
 'G0008_0_S0040.wav': {'text': 'YO ARE WELL AT LEAST WEARE OUT OF THE OFFICE WE HAVE GOT THE PISAR'},
 'G0008_0_S0045.wav': {'text': 'A LOT OF THIS WORK IS VERY DIFFICULT'},
 'G0008_0_S0041.wav': {'text': 'TEN TEN I GOT A TWENTY TAGE THAT'},
 'G0008_0_S0042.wav': {'text': 'BUT MANY PATIENCS NOW LIVE LONGER BEGORS OF IMPROVEMENT'},
 'G0008_0_S0034.wav': {'text': 'MANY FASHION PHRASES CAN BE EITHER POSITIVE OR NEGATIVE'},
 'G0008_0_S0033.wav': {'text': 'DAILOR CLOSED HER NART AMERICAN DURIN TEMPA'},
 'G0008_0_S0032.wav': {'text': 'A LOT OF PEOPLE EAT A GREAT DEEDS OF THESE FOODS'},
 'G0008_0_S0015.wav': {'text': "THEY WERE CHEERIN THE PANTHERS UNSO I ESUME DEAR'S NO REAL RIVALLRY LOL"},
 'G0008_0_S0027.wav': {'text': 'I LEVED THEM TO LOT OF GREAT SONGS'},
 'G0009_0_S0001.wav': {'text': 'FOUR FIVE SIX AT TWO ON SEVEN EIGHT SEVEN FIVE TO AIT ZIRU THREE SEVEN DERO SIX SIX'},
 'G0009_0_S0039.wav': {'text': "IF YOU BY CHICKEN AT A GOOD BUTCER'S"},
 'G0009_0_S0007.wav': {'text': 'FIVE ZERO THREE SIX ONE FIVE TWO SIXT THREE FOR SEVEN SEVEN ONE ZERO AIGHT EIGHT FOR SEVEN'},
 'G0009_0_S0032.wav': {'text': 'AND THERE WAS THE GOL WEARING THAT PLAIN WHITE DRESS AND WHITE COWBO ABOOTS'},
 'G0009_0_S0042.wav': {'text': 'YOU WANT SOME BREAKFAST MEAT MYCO IS THAT WHAT YOU WAN'},
 'G0009_0_S0022.wav': {'text': 'THE PICTURES SHOWED WHAT APPEARED TO BE HIGH EXPLOSIVES IN'},
 'G0009_0_S0041.wav': {'text': 'MUCH SMALLER THAN WAS DONE EVEN AT BRUD HO BABO IN THE ES'},
 'G0009_0_S0015.wav': {'text': 'DO NOT COURODE AND DO NOT REACT WITH TIN'},
 'G0009_0_S0034.wav': {'text': 'OH OKE HAD JOHN CUSACK IN IT I THINK'},
 'G0009_0_S0030.wav': {'text': 'AND SECOND TO ENTER THE IN THE TOP SPOT'},
 'G0009_0_S0026.wav': {'text': 'JOT SHE IS UNIQUE AND THE MUSIC WORD NEEDS MORE SINGLES SINGERS LIKE HER'},
 'G0009_0_S0004.wav': {'text': 'TO THREE THREE DU SEVEN FOUR FIVE FOUR EIGHT SIX ONE FIVE ZIRO T THREE TO ZIRO FOUR'},
 'G0009_0_S0036.wav': {'text': 'YES YOU CAN YOU CAN SPOIL A PERFECTLY NICE DANSE'},
 'G0009_0_S0021.wav': {'text': 'DID YOU KNOW THAT LESLY MAN IS ACTUALLY HIS WIFE IN REAL LIFE'},
 'G0009_0_S0009.wav': {'text': 'ZYROFOUR ONE ZILO THREE SEVEN ONE SEVEN AT TRE FIVE T FIVE SIX EIGHT DO FIVE THREE'},
 'G0009_0_S0013.wav': {'text': 'A GOD DIS JESS AT A TRIPPED STORE FOR ONE DOLLAR'},
 'G0009_0_S0019.wav': {'text': 'IT HAD ITS GOOD PINTS STILL DE LIGHT SABBER BOT BATTLE WAS AMAZING'},
 'G0009_0_S0035.wav': {'text': 'IT WAS REPLACED BY A STORE AND WISTORS CENTERED THAT'},
 'G0009_0_S0008.wav': {'text': 'ONE TOU THREE IT SIXTO SEVEN FOR SEVEN ZIRO SEVEN NAT SIX ONE AIGHT FIVE FOR ZIRO'},
 'G0009_0_S0023.wav': {'text': 'HAVE COST A PER SENT FALL IN THE VALUE OF TERUBLE'},
 'G0005_0_S0017.wav': {'text': 'I WAS JUST WONDERING IF YOU HAPPENED TO KNOW ANYTHING ABOUT BALL SHELDEN'},
 'G0005_0_S0014.wav': {'text': 'IT IS IDEE TO HOW DE NEEDE'},
 'G0005_0_S0001.wav': {'text': 'SIX SEVEN FIVE CEADL FIVE FENZEDL ET EIT ONE SEADL FOUR SIX SEVON VONE FOUR SIX TREE'},
 'G0005_0_S0003.wav': {'text': 'FIVE IN DO TREE SDO SEVEN TREE SIX EIGHT FOUR TREE SIDO FOUR FOR SEX SEVEN SEDO TO'},
 'G0005_0_S0012.wav': {'text': 'AND TRAGTY BADTINGS ABOUT YOUR OPENIND'},
 'G0005_0_S0009.wav': {'text': 'THREE ET SEVEN FIVE SEX SEX DO DO SEX EDO TREE TREE YOU ET EIGHT FOR FIVE FUN'},
 'G0005_0_S0005.wav': {'text': 'FIVE SEVEN EIGHT DU THREE SIX SEVEN ZEDOS SEVEN THREE ONE EAIT ZEDO FOUR EIGHT ONE TWO FIVE'},
 'G0005_0_S0006.wav': {'text': 'SEVEN SIX EIGHT FOUR ZEIDO DU SIX ST SIX EIGHT ONE TREE ZEDO FOUR IS SEVEN EIGHT THREE ONE'},
 'G0005_0_S0016.wav': {'text': 'WHA I JUST ORDERED FROM EMAZONE IS THIS TO BE EXPECTED'},
 'G0005_0_S0019.wav': {'text': 'THINK ABOUT WHAT YOU ARE GOING TO SEE IT ME OUR OWNTIN EYES'},
 'G0005_0_S0010.wav': {'text': 'FIVE SEVEN FOR TREE SIXEDO ET SEVEN DO SEVEN FOR EIT SIX FIVE SIXSEDOR THREE ONE'},
 'G0005_0_S0004.wav': {'text': 'DO ONE SEEDLE SEVEN DO ONE IT FIVE THREE SIX ONE DO ET SIX SEVEN FIE THREE EIGHT'},
 'G0005_0_S0011.wav': {'text': 'I LIKE DAT IT IS SOME WHIT BEAST ON REAL LIFE THOSE ARE ALWAYS HIS CERIEST'},
 'G0005_0_S0007.wav': {'text': 'ONE FIVE SEK SEVEN THREE FOUR ZIDO DU FIVE FIVE SIX FOUR EIGHT SEVON SEMON VANS ETOR ONE'},
 'G0005_0_S0013.wav': {'text': 'BRIGHT DIED ABOUT TO DIMONDS MORE MISSIVE THAN HER SON'},
 'G0005_0_S0015.wav': {'text': 'THE PRICE OF GOBAUT HAS MORE TAN DOUBLED'},
 'G0005_0_S0018.wav': {'text': 'I REMEMBERED THE FIRST TIME I SAW STAR WARS IT BLEW MY MIND'},
 'G0005_0_S0002.wav': {'text': 'CEDO DU TREE AIT SIX THREE FOR SIX EIGHT FOR THREE SEVEN FIVE ONE EIGHT SEVENTH DUZIRO'},
 'G0005_0_S0008.wav': {'text': 'FIVEFOR DU THREE SIX SEVEN DO EC SIX ONE FIVE SEVEN THREE DO THREE EIGT ONE ONE'},
 'G0005_0_S0063.wav': {'text': 'TANG DO MARIGA FOR ONE OF HIS FAVOURITD SONGS'},
 'G0006_0_S0003.wav': {'text': 'SEVEN FOR VAND FIVE SIX CERT VANZILO IG TO SEVEN FIVE FIVE THREE SEVEN TU TOZILO'},
 'G0006_0_S0021.wav': {'text': 'THEREIT WAS A GREAT MOODY IT WAS SO FUNLY'},
 'G0006_0_S0011.wav': {'text': 'WIDE FLAG OF TRUTHS ARLIER IN THERDY'},
 'G0006_0_S0008.wav': {'text': 'SIXZEO SEEN TO THREY SIX ON TWO SAMON TOS ZELO FOUR AIGHT FIVE THREE ERED THREE FIVE'},
 'G0006_0_S0023.wav': {'text': 'BUT BUT YOU SAID YOU ONLY HAD SEX RITIGERS YOU NEVER MENTIONED HIM'},
 'G0006_0_S0009.wav': {'text': 'THREE ART FOR TEE SEVEN FIVE SEVEN FOUR SIXTU THREE TO AN FOUR SIX MON TUZILO'},
 'G0006_0_S0020.wav': {'text': 'HAVING THE NEW FIDE SAN A LARD OF PROBLEMS'},
 'G0006_0_S0024.wav': {'text': "I ACTULLY HAVEN'T SEEN DAT ONE IS IT ANY GOOD"},
 'G0006_0_S0005.wav': {'text': 'TWO AIGT FOR FIVE FIVE SIX SEWAND THREE EIGHT SEVEN SEVEN POR THRI DOSILO THREE ERED FIVE'},
 'G0006_0_S0004.wav': {'text': 'ZEAL OF SIX FIVE FOR TO SEVEN FIVE FIVE ONE FOR SEVEN TO THREE AR TO SIX VONDILO'},
 'G0006_0_S0019.wav': {'text': 'HE GORED IN THE BELLY HEIS STILL ALIVE BUT FORNED ME FORT LONG'},
 'G0006_0_S0015.wav': {'text': 'AND GOD BLESSD THE UNITED STARTS OF OMEDICA'},
 'G0006_0_S0007.wav': {'text': 'SIX ERD FOR THREE SEVEN FOR THREE ZEL O THREE FIVE FIVE TO SIX TOSIL OF FIVE ONE ONE'},
 'G0006_0_S0002.wav': {'text': 'FOUR DI O FIVE SIXT FIVE DO DU VANDIO ZIO EIGT THREE SEVEN SIXSIX EIGHT FIVE SEVEN'},
 'G0006_0_S0006.wav': {'text': 'TASEO SIXCERED FIVE TREE TO SIX TWO EIGT ONE SIX ONE ONE TWO EITZEAL OF FIVE'},
 'G0006_0_S0013.wav': {'text': 'YAH A DERED SNARD LIKE YOUGOD AND ERED IN THE YELLOU PIGES'},
 'G0006_0_S0017.wav': {'text': 'I AGREE WHAT DO YOU THINK ABOUT DHER NEW QUATREBEC'},
 'G0006_0_S0016.wav': {'text': 'AND PARTLY BECAUSE OF THE RETIAL HATRED THI AR ARON TEM'},
 'G0006_0_S0001.wav': {'text': 'ZEROZIRO THREE FOR SEVEN SEVEN FIVE FIVE THREE SEVEN ONE FOR THREE FOR SIX TO FIFERD'},
 'G0006_0_S0012.wav': {'text': 'YA HE WAS DREGOIN PROMITIURS IS HE IN IT'},
 'G0001_0_S0123.wav': {'text': "I KIND HAVE THOUGHT IT WOULD BE BETTER THAN THE SECOND BUT IT'S REALLY NOT"},
 'G0001_0_S0124.wav': {'text': 'THINGS BEGIN TO CHANGE IN THE LATE ES'},
 'G0001_0_S0102.wav': {'text': 'YER HE WAS EVERYWERE THEN EVEN MY MOMENSIN TO HIM BEGGDIN'},
 'G0001_0_S0119.wav': {'text': 'PELASTINIANS WON THEIR OWN STATE IN ALL OF THE WIST'},
 'G0001_0_S0132.wav': {'text': 'THE CARS REASERTERED THEIR RIS TO THE ATY AFTER YOU'},
 'G0001_0_S0109.wav': {'text': 'FROM THAT TIME UNTIL SHE WAS ALMOST SEVEN YEARS OLD'},
 'G0001_0_S0114.wav': {'text': "DID THE MONSTRATORS REAVE THE LEBONY'S BLAG AT THE SIGN OF UNITY"},
 'G0001_0_S0104.wav': {'text': "SHE LOOKED LIKE THE GY FROM BYMEAT'S ROAR WITH A WIG ON"},
 'G0001_0_S0108.wav': {'text': 'WE HAVE TO PROSED AND HAVE TO GON TONUW'},
 'G0001_0_S0130.wav': {'text': 'COME ON MAN HOW AN AR DID YOU NOT TO THE PSYRCASM'},
 'G0001_0_S0115.wav': {'text': 'ELESSEN CHILDREN DIED OF EAS IN HIGH INCOME COUNTRIES'},
 'G0001_0_S0117.wav': {'text': 'HAVE YO YOU ENHEARD THE AMERICAN ENGLISH EDIUMS'},
 'G0001_0_S0113.wav': {'text': 'YES AFTER A LOT OF EGXST THE END OP GOING AFTER A YOUNG COUPLE'},
 'G0001_0_S0126.wav': {'text': 'I HOLD MY CRABBS LIKE IAM A SANDRICH'},
 'G0001_0_S0134.wav': {'text': 'JOHN GANNY HE AND STAVEMARDIN ARE REALLY THE ONLY DO IN IT BESIDES EXTRESS'},
 'G0001_0_S0136.wav': {'text': 'BARD OR ALL OF THE GINDLS ARE REMOVED'},
 'G0001_0_S0118.wav': {'text': 'AS THE NEW YEARD CELIBRATIONS COME TO AN END'},
 'G0001_0_S0101.wav': {'text': 'HAS EXPERIENCED IN MARTHENJUSED TECHNICAL INTELLIGENCE'},
 'G0001_0_S0105.wav': {'text': 'THIS IS NOT THE TIME OR THE PLAYS TO HAVE THE SAME OR DISCUSSION'},
 'G0001_0_S0129.wav': {'text': "MY GUARD HE'S GOING AFTER THE NIST"},
 'G0004_0_S0017.wav': {'text': 'WHO ARE YOU DOCTOR ARTHAMS MARS SPORS DO ASSIST ME'},
 'G0004_0_S0029.wav': {'text': 'BUT AUNT IS THY SUPREME CORD AND THY FERDILE GORD SYSTOM'},
 'G0004_0_S0016.wav': {'text': 'THERE HAS TO BE MORE TUE DONE'},
 'G0004_0_S0033.wav': {'text': "NO I GET YOU I MEANS IT'S FOR SEVERL JUST KEEPING UP WIT THY BIG HOLYROUD WOVIES"},
 'G0004_0_S0006.wav': {'text': 'THEDO SAMON TEDO SEX TO ONE ONE FOR THREE TWO SEVEN ZEADO FIVE TO FOR EIGHT'},
 'G0004_0_S0013.wav': {'text': 'IT BEGAN MAN IMIDATE BEST SALORD AND REMAINS POPULAR TO DAY'},
 'G0004_0_S0021.wav': {'text': 'DO ME UP HER WIL GO BACK AN QUIRTE ME FROM VERE I SAID POLOGISE'},
 'G0004_0_S0030.wav': {'text': 'NOD ONE INCH SHOWED WE GIVE TO HIS PEOPLE'},
 'G0004_0_S0037.wav': {'text': 'NO I WAS HOPING THE GOLDS WOULD GAD DO MAKE AR SHOT AT HIM'},
 'G0004_0_S0015.wav': {'text': 'GAVES A HOME TO SOME OF THOU SETRINGEST GITIA YERS OR NOT'},
 'G0004_0_S0004.wav': {'text': 'ONE ZEALO SIX TWO EIGHT FIVE SEVEN TWO SEVEN SIX TO SEVEN FIVE FOUR THREE ZEADLE'},
 'G0004_0_S0012.wav': {'text': "GAN OD SIRTIFI DAPIESEFUL NATURE OF ERANT'S NEWCLER PROGRAM"},
 'G0004_0_S0020.wav': {'text': "I THINK IT'S THO MOST COMPLITATED OF THAR THREE I CRIPPING"},
 'G0004_0_S0007.wav': {'text': 'ZELOS LO ON DO ARD SAVON SAON AT SAVEN TO FIVE THREE WUDE FORD FOR'},
 'G0004_0_S0014.wav': {'text': "YOU MENTION UP YUR RIGT ARE AL OF THE POSITION BLAED IN BAT'S BOL"},
 'G0004_0_S0008.wav': {'text': 'ONE TWO THREE TWO SEVEN SIX SEEDO FIVE THREE DOZEDO EIGHT FIVE SEVENTHEVONE'},
 'G0004_0_S0040.wav': {'text': 'HUMAN DESTING IS TILL THREE TO FIVE YEARS AR AGE'},
 'G0004_0_S0032.wav': {'text': 'THE FIRST A MAN WANT MIGHT NO EXIST AT ALL'},
 'G0004_0_S0039.wav': {'text': 'AND THE TELL YOU YOU HAVE OUR CHANCE TOVIN A LAPD UP'},
 'G0004_0_S0041.wav': {'text': 'CAUSED HARD FEELINGS AMONG BOLIDIGALUDORS IN OTHER STATS'}}

In [ ]:
# Calculate total time taken in seconds
total_time = end_time - start_time

# Print the total time taken
print(f"Total time taken for transcription: {total_time:.2f} seconds")

Total time taken for transcription: 510.97 seconds

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/FYP/transcriptions_comparison.csv')
df.head()

,id,predicted_transcription,original_transcription,predicted_transcription_wav2vec2
0,G0007_0_S0020.wav,Give up steps that hinder normal development ...,give up steps that hinder normal development i...,GIVE UP STEPS THAT HINDER NORMAR DEVELOPMENT I...
1,G0007_0_S0023.wav,The car's solar panel creates electricity fro...,the car's solar panel creates electricity from...,THE GARDS SOLER BANNA TR YEAR'S ELECTRICITY FR...
2,G0007_0_S0031.wav,"The rebel was Elvis Persley, the king of rock...",the rebel was elvis presley the king of rock a...,TA RUBELL ROS ALVAS BURSTLY THE KING OF ROKINROD
3,G0007_0_S0005.wav,747-76-53604-3-30-26-16-1781,seven four seven six five three six zero four ...,SEVON FOUR SEVON SIX FIVE THREE SIX DEO FOR TH...
4,G0007_0_S0006.wav,4768-18-0252-0-0352-0365-04-46,four seven six eight one eight zero two five t...,FOUR SAON SIX EIGHTH TO ONE EIGTH LIDO DU FIVE...

In [ ]:

# Step 2: Create a new column 'transcription' based on the 'id' column matching dictionary keys
df['predicted_transcription_wav2vec2'] = df['id'].map(lambda x: predicted_transcriptions.get(x, {}).get('text', 'No transcription found'))

#df['predicted_transcription_wav2vec2'] = df['predicted_transcription_wav2vec2'].str.strip()

# Step 3: Save the updated DataFrame back to the CSV file (overwrite the original file)
#df.to_csv('/content/drive/MyDrive/FYP/transcriptions_comparison.csv', index=False) Done

In [ ]:
from transformers.models.whisper.english_normalizer import BasicTextNormalizer

normalizer = BasicTextNormalizer()

df['normalized_transcription_wav2vec2'] = df['predicted_transcription_wav2vec2'].apply(normalizer)

In [ ]:
# Initialize the WER metric
wer_metric = load("wer")

wer_ortho = 100 * wer_metric.compute(
    references=df['original_transcription'], predictions=df['normalized_transcription_wav2vec2'])

print(f"Word Error Rate (WER): {wer_ortho}%")

Word Error Rate (WER): 39.667630057803464%

In [ ]:
df[['normalized_transcription_wav2vec2', 'original_transcription']].iloc[1:20,:]

,normalized_transcription_wav2vec2,original_transcription
1,the gards soler banna tr year s electricity fr...,the car's solar panel creates electricity from...
2,ta rubell ros alvas burstly the king of rokinrod,the rebel was elvis presley the king of rock a...
3,sevon four sevon six five three six deo for th...,seven four seven six five three six zero four ...
4,four saon six eighth to one eigth lido du five...,four seven six eight one eight zero two five t...
5,and ic todi of chef joseph of tha nesberss ind...,and its story of jeff joseph of the nez perce ...
6,hangs for playing alone i just have to sit for...,thanks for playing along i just have to sit fo...
7,mone pessenger died after being barshly out of...,one passenger died after being partially out o...
8,no no i have to go now i have to see the phroz...,now now i have to go now i have to see the fro...
9,and she tanked e franch peaper for shiring hig...,and she thanked the french people for sharing ...
10,i laughed so hard so you made me coke on the f...,i laughed so hard so you made me choke on the ...
11,i am a fresh grat with no religid experience s...,i am a fresh grad with no related experience s...
12,the girl is for people ito cat to kno each,the goal is for people to get to know each
13,i highly doubt it i would think that they are ...,i highly doubt it i would think that they're a...
14,one zero five eighth four salmon seero three s...,one zero five eight four seven zero three seve...
15,no it is hard every year in grant prank in chi...,now it is held every year in grant park in chi...
16,three do vizero four eighth seven five zedo do...,three two zero four eight seven five zero two ...
17,eight eight seven four sevone one zeadle three...,eight eight seven four seven one zero three on...
18,yup i hamvered listen too much of him but so f...,yep i haven't listened too much of him but so ...
19,no but i have heard off it is it good,no but i have heard of it is it good

**Wav2vec2N-gram**

In [ ]:
!pip install pyctcdecode pypi-kenlm

Collecting pyctcdecode
  Downloading pyctcdecode-0.5.0-py2.py3-none-any.whl.metadata (20 kB)
Collecting pypi-kenlm
  Downloading pypi-kenlm-0.1.20220713.tar.gz (278 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.4/278.4 kB 11.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy<2.0.0,>=1.15.0 in /usr/local/lib/python3.10/dist-packages (from pyctcdecode) (1.26.4)
Collecting pygtrie<3.0,>=2.1 (from pyctcdecode)
  Downloading pygtrie-2.5.0-py3-none-any.whl.metadata (7.5 kB)
Collecting hypothesis<7,>=6.14 (from pyctcdecode)
  Downloading hypothesis-6.118.8-py3-none-any.whl.metadata (6.0 kB)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.10/dist-packages (from hypothesis<7,>=6.14->pyctcdecode) (24.2.0)
Collecting sortedcontainers<3.0.0,>=2.1.0 (from hypothesis<7,>=6.14->pyctcdecode)
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: exceptiongroup>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from hypothesis<7,>=6.14->pyctcdecode) (1.2.2)
Downloading pyctcdecode-0.5.0-py2.py3-none-any.whl (39 kB)
Downloading hypothesis-6.118.8-py3-none-any.whl (471 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 471.8/471.8 kB 22.4 MB/s eta 0:00:00
Downloading pygtrie-2.5.0-py3-none-any.whl (25 kB)
Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Building wheels for collected packages: pypi-kenlm
  Building wheel for pypi-kenlm (setup.py) ... done
  Created wheel for pypi-kenlm: filename=pypi_kenlm-0.1.20220713-cp310-cp310-linux_x86_64.whl size=2935996 sha256=0ca94c0bcd8bfd0588eb4ff4f27a69cb5a739b521842a8025e147efaa5436cda
  Stored in directory: /root/.cache/pip/wheels/24/6c/ca/e305540f351405de41fe750ab134480a3646f3eff3f441d4f6
Successfully built pypi-kenlm
Installing collected packages: sortedcontainers, pypi-kenlm, pygtrie, hypothesis, pyctcdecode
Successfully installed hypothesis-6.118.8 pyctcdecode-0.5.0 pygtrie-2.5.0 pypi-kenlm-0.1.20220713 sortedcontainers-2.4.0

In [ ]:
# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("automatic-speech-recognition", model="patrickvonplaten/wav2vec2-base-100h-with-lm")

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

alphabet.json:   0%|          | 0.00/198 [00:00<?, ?B/s]

language_model/attrs.json:   0%|          | 0.00/78.0 [00:00<?, ?B/s]

language_model/unigrams.txt:   0%|          | 0.00/1.74M [00:00<?, ?B/s]

4-gram.bin:   0%|          | 0.00/3.12G [00:00<?, ?B/s]

In [ ]:
# Start the timer
start_time = time.time()

# Initialize dictionary to store the predicted transcriptions
predicted_transcriptions = {}

# Loop over each .wav file in wav_files
for wav_file in wav_files:
    transcription = pipe(wav_file)

    # Get the file name (ID) from the full path
    wav_id = os.path.basename(wav_file)

    # Store the transcription in the dictionary
    predicted_transcriptions[wav_id] = transcription

# Stop the timer after processing all files
end_time = time.time()

In [ ]:
# Calculate total time taken in seconds
total_time = end_time - start_time

# Print the total time taken
print(f"Total time taken for transcription: {total_time:.2f} seconds")

Total time taken for transcription: 421.40 seconds

In [ ]:

# Step 2: Create a new column 'transcription' based on the 'id' column matching dictionary keys
df['predicted_transcription_wav2vec2Ngram'] = df['id'].map(lambda x: predicted_transcriptions.get(x, {}).get('text', 'No transcription found'))

#df['predicted_transcription_wav2vec2'] = df['predicted_transcription_wav2vec2'].str.strip()

# Step 3: Save the updated DataFrame back to the CSV file (overwrite the original file)
#df.to_csv('/content/drive/MyDrive/FYP/transcriptions_comparison.csv', index=False)

In [ ]:
df.head()

,id,predicted_transcription,original_transcription,predicted_transcription_wav2vec2,normalized_transcription_wav2vec2,predicted_transcription_wav2vec2Ngram
0,G0007_0_S0020.wav,Give up steps that hinder normal development ...,give up steps that hinder normal development i...,GIVE UP STEPS THAT HINDER NORMAR DEVELOPMENT I...,give up steps that hinder normar development i...,GIVE UP STEPS THAT HINDER NORMAL DEVELOPMENT I...
1,G0007_0_S0023.wav,The car's solar panel creates electricity fro...,the car's solar panel creates electricity from...,THE GARDS SOLER BANNA TR YEAR'S ELECTRICITY FR...,the gards soler banna tr year s electricity fr...,THE GUARDS SOLER BANNER THREE YEARS ELECTRICIT...
2,G0007_0_S0031.wav,"The rebel was Elvis Persley, the king of rock...",the rebel was elvis presley the king of rock a...,TA RUBELL ROS ALVAS BURSTLY THE KING OF ROKINROD,ta rubell ros alvas burstly the king of rokinrod,THE REBEL ROSE ALVA BURSTLY THE KING OF ROKENROD
3,G0007_0_S0005.wav,747-76-53604-3-30-26-16-1781,seven four seven six five three six zero four ...,SEVON FOUR SEVON SIX FIVE THREE SIX DEO FOR TH...,sevon four sevon six five three six deo for th...,SEVEN FOUR SEVEN SIX FIVE THREE SIX ZERO FOUR ...
4,G0007_0_S0006.wav,4768-18-0252-0-0352-0365-04-46,four seven six eight one eight zero two five t...,FOUR SAON SIX EIGHTH TO ONE EIGTH LIDO DU FIVE...,four saon six eighth to one eigth lido du five...,FOR SALMON SIX EIGHT TO ONE EIGHTH LIDODU FIVE...

In [ ]:
normalizer = BasicTextNormalizer()

df['normalized_transcription_wav2vec2Ngram'] = df['predicted_transcription_wav2vec2Ngram'].apply(normalizer)

In [ ]:
# Initialize the WER metric
wer_metric = load("wer")

wer_ortho = 100 * wer_metric.compute(
    references=df['original_transcription'], predictions=df['normalized_transcription_wav2vec2Ngram'])

print(f"Word Error Rate (WER): {wer_ortho}%")

Word Error Rate (WER): 26.300578034682083%

In [ ]:
df[['normalized_transcription_wav2vec2Ngram', 'original_transcription']].iloc[50:70,:]

,normalized_transcription_wav2vec2Ngram,original_transcription
50,jot she is unique and the music word needs mor...,truth she is unique and the music world needs ...
51,two three three two seven four five four eight...,two three three two seven four five four eight...
52,yes you can you can spoil a perfectly nice dance,yes you can you can spoil a perfectly nice dance
53,did you know that lesly man is actually his wi...,did you know that leslie mann is actually his ...
54,zero four one zelo three seven one seven at th...,zero four one zero three seven one seven eight...
55,a god dis jes at a tripped store for one dollar,i got this dress at a thrift store for one dollar
56,it had its good points still delights saber bu...,it had it's good points though the light saber...
57,it was replaced by a store and visitors center...,it was replaced by a store and visitors center...
58,one two three at six to seven for seven zero s...,one two three eight six two seven four seven z...
59,have cost a per cent fall in the value of the ...,have caused a percent fall in the value of the...
60,i was just wondering if you happened to know a...,i was just wondering if you happen to know any...
61,it is i dee to how the needy,it is a day to help the needy
62,six seven five seat five fenced eight eight on...,six seven five zero five one zero eight eight ...
63,five in de tree so seven three six eight four ...,five one two three zero seven three six eight ...
64,and tracy bad things about your open and,and try say bad things about your opponent
65,three eight seven five six six to do six edo t...,three eight seven five six six two two six zer...
66,five seven eight do three six seven zero seven...,five seven eight two three six seven zero seve...
67,seven six eight four zed do six to six eight o...,seven six eight four zero two six two six eigh...
68,why i just ordered from amazon is this to be e...,wow i just ordered from amzon is this to be ex...
69,think about what you are going to see it be ou...,think about what you're going to say add we ar...

# **Whiser distil small en**

In [ ]:
# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("automatic-speech-recognition", model="distil-whisper/distil-small.en")

config.json:   0%|          | 0.00/2.26k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/332M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/1.92k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/282k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/999k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.41M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

normalizer.json:   0%|          | 0.00/52.7k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.17k [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/339 [00:00<?, ?B/s]

Device set to use cpu

In [ ]:
def transcribe_speech(filepath):
    output = pipe(
        filepath,
        max_new_tokens=256,
        chunk_length_s=30,
        batch_size=8,
    )
    return output["text"]

In [ ]:
# Start the timer
start_time = time.time()

# Initialize dictionary to store the predicted transcriptions
predicted_transcriptions = {}

# Loop over each .wav file in wav_files
for wav_file in wav_files:
    # Call the transcribe function to get the transcription for each wav file
    transcription = transcribe_speech(wav_file)

    # Get the file name (ID) from the full path
    wav_id = os.path.basename(wav_file)

    # Store the transcription in the dictionary
    predicted_transcriptions[wav_id] = transcription

# Stop the timer after processing all files
end_time = time.time()

/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(

In [ ]:
predicted_transcriptions

{'G0007_0_S0020.wav': ' Give up steps that hinder normal development in relations.',
 'G0007_0_S0023.wav': " The car's solar panel creates electricity from sunlight.",
 'G0007_0_S0031.wav': " The rebel was Elvis Persley, the king of Rockin' Road.",
 'G0007_0_S0005.wav': ' 7476560433030261781',
 'G0007_0_S0006.wav': ' 4-7-6-8-1-8-0-2-2-3-6-5-044-6',
 'G0007_0_S0024.wav': ' and its story of Chief Joseph of the Naspurs Indians.',
 'G0007_0_S0040.wav': ' Thanks for playing along. I just have to sit for a while.',
 'G0007_0_S0043.wav': ' One passenger died after being partially out of the plane.',
 'G0007_0_S0018.wav': ' Now, now I have to go now. I have to see the frozen Charles now tonight.',
 'G0007_0_S0042.wav': ' And she thanked the French people for sharing her despair.',
 'G0007_0_S0013.wav': ' I laughed so hard so you made me joke on the food I am eating.',
 'G0007_0_S0027.wav': ' I am a fresh grad with no relative experience so yes, Lawl.',
 'G0007_0_S0025.wav': ' The goal is for people to get to know each.',
 'G0007_0_S0037.wav': ' I highly doubt it. I would think that they are all just on a normal Saturday.',
 'G0007_0_S0004.wav': ' 1058470377624.125281',
 'G0007_0_S0033.wav': ' Now it is held every year in Grand Prang in Chicago.',
 'G0007_0_S0003.wav': ' 3204875046.046237.543',
 'G0007_0_S0007.wav': ' 88747103122447066',
 'G0007_0_S0022.wav': " Yep, I haven't listened too much of him but so far I suppose it's okay.",
 'G0007_0_S0038.wav': ' No, but I have heard of it. Is it good?',
 'G0008_0_S0024.wav': ' Right now we now have 12 students to purdue.',
 'G0008_0_S0049.wav': ' Who do you think the wolves and the Mavericks will take?',
 'G0008_0_S0047.wav': " And no, it's not as if any of her already early stuff was less provocative.",
 'G0008_0_S0016.wav': ' She looked down her nose at me and sneered.',
 'G0008_0_S0043.wav': " Yes, that's it. I'd like that one. What about Benny Goodman? You mentioned earlier.",
 'G0008_0_S0025.wav': " I didn't know it was an impulse me wearing my good shoes.",
 'G0008_0_S0023.wav': " Knox, oh yes Knox, I'm glad you called.",
 'G0008_0_S0017.wav': " Well, we are starving. Why don't we all go to get something to eat?",
 'G0008_0_S0028.wav': ' and the recommendation of their doctors are on their own.',
 'G0008_0_S0048.wav': ' I like everything since equally they are all great',
 'G0008_0_S0037.wav': ' I really doubt they can lift mountains without multiple people having to do it.',
 'G0008_0_S0040.wav': ' Yeah, well at least we are out of the office. We have got the pizzer.',
 'G0008_0_S0045.wav': ' A lot of this work is very difficult.',
 'G0008_0_S0041.wav': ' 10 10 I got a 20 take that',
 'G0008_0_S0042.wav': ' But many patients now live longer because of improvements.',
 'G0008_0_S0034.wav': ' Many fashion phrases can be either positive or negative.',
 'G0008_0_S0033.wav': ' Taylor closed her North American tour in Tampa.',
 'G0008_0_S0032.wav': ' A lot of people eat a great deal of these foods.',
 'G0008_0_S0015.wav': " They were cheering the Panthers until I assume there's no real rivalry lull.",
 'G0008_0_S0027.wav': ' I love them to a lot of great songs.',
 'G0009_0_S0001.wav': ' 456-2-178752-8-0-37066',
 'G0009_0_S0039.wav': " If you buy chicken at a good butcher's",
 'G0009_0_S0007.wav': ' 503615263477108847',
 'G0009_0_S0032.wav': ' And there was the girl wearing that plain white dress and white cowboy boots.',
 'G0009_0_S0042.wav': ' You want some breakfast meat? Michael, is that what you want?',
 'G0009_0_S0022.wav': ' The pictures showed what appeared to be high explosives in.',
 'G0009_0_S0041.wav': ' Much smaller than was done even at Prudho Beebok in the S.',
 'G0009_0_S0015.wav': ' Do not corrode and do not react with tin.',
 'G0009_0_S0034.wav': ' Oh, okay. Had John Cusack in it, I think.',
 'G0009_0_S0030.wav': ' and second to enter the in the top spot.',
 'G0009_0_S0026.wav': ' Trot, he is unique and the music world needs more singers like her.',
 'G0009_0_S0004.wav': ' 233274586150833 204',
 'G0009_0_S0036.wav': ' Yes you can, you can spoil a perfectly nice dance.',
 'G0009_0_S0021.wav': ' Did you know that Leslie Mann is actually his wife in real life?',
 'G0009_0_S0009.wav': ' 0.4.1037178358568253.',
 'G0009_0_S0013.wav': ' I got this dress at a thrift store for $1.',
 'G0009_0_S0019.wav': ' It had its good points to the Light Sabbath battle was amazing.',
 'G0009_0_S0035.wav': ' It was replaced by a store and visitor center that.',
 'G0009_0_S0008.wav': ' 1-2-3-8-6-2-7-4-7-0-7-86-1-86-1-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2222-2-22222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222',
 'G0009_0_S0023.wav': ' have caused a person fall in the value of the rubble.',
 'G0005_0_S0017.wav': ' I was just wondering if you happen to know anything about Paul Sheldon?',
 'G0005_0_S0014.wav': ' It is a day to help the needy.',
 'G0005_0_S0001.wav': ' 675051088104671463',
 'G0005_0_S0003.wav': ' 51230368430446702',
 'G0005_0_S0012.wav': ' And trash say bad things about your opponent.',
 'G0005_0_S0009.wav': ' 3 87566-22-6033-088451',
 'G0005_0_S0005.wav': ' 57826707318048125',
 'G0005_0_S0006.wav': ' 768402668-1-304731',
 'G0005_0_S0016.wav': ' Wow, I just ordered from Amazon. Is this to be expected?',
 'G0005_0_S0019.wav': ' Think about what you are going to see and we are on thin eyes.',
 'G0005_0_S0010.wav': ' 57436072748656031',
 'G0005_0_S0004.wav': ' 21072-853612867538.',
 'G0005_0_S0011.wav': ' I like that it is somewhat based on real life those are always the scariest.',
 'G0005_0_S0007.wav': ' 567 34025564877101',
 'G0005_0_S0013.wav': ' Bright starred about two times more massive thinner sun.',
 'G0005_0_S0015.wav': ' The price of Cobalt has more than doubled.',
 'G0005_0_S0018.wav': ' I remember the first time I saw Star Wars it blew my mind.',
 'G0005_0_S0002.wav': ' 0-2-3-86-3-4-6-6-84-6-6-3-6-3-6-3-6-3-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-',
 'G0005_0_S0008.wav': ' 542, 236, 6, 2, 8, 6, 573, 2, 3, 3, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2',
 'G0005_0_S0063.wav': ' Thanked America for one of his favorite songs.',
 'G0006_0_S0003.wav': ' 7415681082755372220',
 'G0006_0_S0021.wav': ' That was a great movie. It was so funny.',
 'G0006_0_S0011.wav': ' White flag of truth earlier in the day.',
 'G0006_0_S0008.wav': ' 607236272 048353835',
 'G0006_0_S0023.wav': ' But what you said, you only had sex with three guys, you never mentioned him.',
 'G0006_0_S0009.wav': ' 3 at 4-3-7-5-7, 4-6-2, 3-2, 3-2, 2-0.',
 'G0006_0_S0020.wav': ' Having the new pipe solved a lot of problems.',
 'G0006_0_S0024.wav': " I actually haven't seen that one. Is it any good?",
 'G0006_0_S0005.wav': ' 284556-73872323-20385',
 'G0006_0_S0004.wav': ' 0.654-27551423-82610.',
 'G0006_0_S0019.wav': " He got in the belly. He is still alive but won't be far long.",
 'G0006_0_S0015.wav': ' And God bless the United States of America.',
 'G0006_0_S0007.wav': ' 684-37-4-303526-2-0-511',
 'G0006_0_S0002.wav': ' 4056522100836666857',
 'G0006_0_S0006.wav': ' 306853262816112805',
 'G0006_0_S0013.wav': " Yeah, Eddie, it's not like you got an ad in the yellow pages.",
 'G0006_0_S0017.wav': ' I agree what do you think about their new quarterback?',
 'G0006_0_S0016.wav': ' and partially because of the racial hatred they saw around them.',
 'G0006_0_S0001.wav': ' 0.347755371436258.',
 'G0006_0_S0012.wav': ' Yeah, he was really good in Prometheus. Is he in it?',
 'G0001_0_S0123.wav': " I kind of thought it would be better than the second but it's really not.",
 'G0001_0_S0124.wav': ' Things begin to change in the latest.',
 'G0001_0_S0102.wav': ' Yeah, he was everywhere then even my mom listened to him back then.',
 'G0001_0_S0119.wav': ' Palestinians won their own state in all of the West.',
 'G0001_0_S0132.wav': ' The Kurds re-asserted their rights to the area after you.',
 'G0001_0_S0109.wav': ' From that time until she was almost 7 years old.',
 'G0001_0_S0114.wav': ' The demonstrators waved the Lebanese flag at the sign of unity.',
 'G0001_0_S0104.wav': ' She looks like the guy from Bai meets war with a wig on.',
 'G0001_0_S0108.wav': ' We have to proceed and have to continue.',
 'G0001_0_S0130.wav': ' Come on man, how on earth did you not see the sarcasm?',
 'G0001_0_S0115.wav': ' Less than children died of age in high-income countries.',
 'G0001_0_S0117.wav': ' Have you even heard the American English idioms?',
 'G0001_0_S0113.wav': ' Yes, after a lot of angst, they end up going after a young couple.',
 'G0001_0_S0126.wav': " I hold my crabs like I'm a sandwich.",
 'G0001_0_S0134.wav': ' John Canny, he and Steve Madden are really the only two in it besides extras.',
 'G0001_0_S0136.wav': ' Part or all of the genitals are removed.',
 'G0001_0_S0118.wav': ' As the new year celebrations come to an end,',
 'G0001_0_S0101.wav': ' Has experience in more than just technical intelligence?',
 'G0001_0_S0105.wav': ' This is not the time or the place to have the same old discussion.',
 'G0001_0_S0129.wav': ' My God, he is going after the nest.',
 'G0004_0_S0017.wav': ' Who are you, doctors? Adems, was supposed to assist me.',
 'G0004_0_S0029.wav': ' Branch is the Supreme Court and the Federal Court system.',
 'G0004_0_S0016.wav': ' There has to be more to be done.',
 'G0004_0_S0033.wav': " No, I get you. I mean it's possible just keeping up with the big Hollywood movies.",
 'G0004_0_S0006.wav': ' 0 7 0 6 2 1 1 4 3 2 7 5 2 4 8',
 'G0004_0_S0013.wav': ' It became an immediate best seller and remains popular today.',
 'G0004_0_S0021.wav': ' Do me a favor, go back and quiet me from where I said apologize.',
 'G0004_0_S0030.wav': ' Not one inch showed we gave to these people.',
 'G0004_0_S0037.wav': ' No, I was hoping the Colts would get to make a shot at him.',
 'G0004_0_S0015.wav': ' Caves are home to some of the largest creatures on earth.',
 'G0004_0_S0004.wav': ' 10628572726275. 430.',
 'G0004_0_S0012.wav': " Can note certify the peaceful nature of Iran's nuclear program?",
 'G0004_0_S0020.wav': " I think it's the most complicated of the three it's creeping.",
 'G0004_0_S0007.wav': ' 0 1 2 8 7 7 7 8 7 8 7 2 5 5',
 'G0004_0_S0014.wav': ' You mention a picture, what are all of the positions played in baseball?',
 'G0004_0_S0008.wav': ' 1 2 3 2 7 6 0 5 3 2 2 8 5 7 3 1',
 'G0004_0_S0040.wav': ' Human testing is still three to five years away.',
 'G0004_0_S0032.wav': ' The First Amendment might not exist at all.',
 'G0004_0_S0039.wav': ' And they tell you you have a chance to win a laptop.',
 'G0004_0_S0041.wav': ' caused hard feelings among political leaders in other states.'}

In [ ]:
# Calculate total time taken in seconds
total_time = end_time - start_time

# Print the total time taken
print(f"Total time taken for transcription: {total_time:.2f} seconds")

Total time taken for transcription: 815.24 seconds

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/FYP/transcriptions_comparison.csv')

In [ ]:

# Step 2: Create a new column 'transcription' based on the 'id' column matching dictionary keys
df['predicted_transcription_Whisper-med-en'] = df['id'].map(predicted_transcriptions)

df['predicted_transcription_Whisper-med-en'] = df['predicted_transcription_Whisper-med-en'].str.strip()

# Step 3: Save the updated DataFrame back to the CSV file (overwrite the original file)
#df.to_csv('/content/drive/MyDrive/FYP/transcriptions_comparison.csv', index=False)

In [ ]:
normalizer = BasicTextNormalizer()

df['normalized_predicted_transcription_Whisper-med-en'] = df['predicted_transcription_Whisper-med-en'].apply(normalizer)

In [ ]:
df.head()

,id,predicted_transcription,original_transcription,predicted_transcription_wav2vec2,normalized_transcription_wav2vec2,predicted_transcription_wav2vec2Ngram,predicted_transcription_Whisper-med-en,normalized_predicted_transcription_Whisper-med-en
0,G0007_0_S0020.wav,Give up steps that hinder normal development ...,give up steps that hinder normal development i...,GIVE UP STEPS THAT HINDER NORMAR DEVELOPMENT I...,give up steps that hinder normar development i...,GIVE UP STEPS THAT HINDER NORMAL DEVELOPMENT I...,Give up steps that hinder normal development i...,give up steps that hinder normal development i...
1,G0007_0_S0023.wav,The car's solar panel creates electricity fro...,the car's solar panel creates electricity from...,THE GARDS SOLER BANNA TR YEAR'S ELECTRICITY FR...,the gards soler banna tr year s electricity fr...,THE GUARDS SOLER BANNER THREE YEARS ELECTRICIT...,The car's solar panel creates electricity from...,the car s solar panel creates electricity from...
2,G0007_0_S0031.wav,"The rebel was Elvis Persley, the king of rock...",the rebel was elvis presley the king of rock a...,TA RUBELL ROS ALVAS BURSTLY THE KING OF ROKINROD,ta rubell ros alvas burstly the king of rokinrod,THE REBEL ROSE ALVA BURSTLY THE KING OF ROKENROD,"The rebel was Elvis Persley, the king of Rocki...",the rebel was elvis persley the king of rockin...
3,G0007_0_S0005.wav,747-76-53604-3-30-26-16-1781,seven four seven six five three six zero four ...,SEVON FOUR SEVON SIX FIVE THREE SIX DEO FOR TH...,sevon four sevon six five three six deo for th...,SEVEN FOUR SEVEN SIX FIVE THREE SIX ZERO FOUR ...,7476560433030261781,7476560433030261781
4,G0007_0_S0006.wav,4768-18-0252-0-0352-0365-04-46,four seven six eight one eight zero two five t...,FOUR SAON SIX EIGHTH TO ONE EIGTH LIDO DU FIVE...,four saon six eighth to one eigth lido du five...,FOR SALMON SIX EIGHT TO ONE EIGHTH LIDODU FIVE...,4-7-6-8-1-8-0-2-2-3-6-5-044-6,4 7 6 8 1 8 0 2 2 3 6 5 044 6

In [ ]:
# Initialize the WER metric
wer_metric = load("wer")

# Function to check if a transcription contains digits
def contains_digits(text):
    # Return True if the text contains any digits
    return bool(re.search(r'\d', text))

# Step 1: Filter out rows where 'normalized_transcription' contains any digits
df_cleaned = df[~df['normalized_predicted_transcription_Whisper-med-en'].apply(contains_digits)]

# Step 2: Calculate WER on the cleaned data
wer_ortho = 100 * wer_metric.compute(
    references=df_cleaned['original_transcription'], predictions=df_cleaned['normalized_predicted_transcription_Whisper-med-en'])

print(f"Word Error Rate (WER): {wer_ortho}%")

Downloading builder script:   0%|          | 0.00/4.49k [00:00<?, ?B/s]

Word Error Rate (WER): 14.441747572815533%

**Whisper Samll en**

In [ ]:
# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("automatic-speech-recognition", model="openai/whisper-small.en")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/1.94k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/967M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/1.93k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/805 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.41M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

normalizer.json:   0%|          | 0.00/52.7k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/1.83k [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/185k [00:00<?, ?B/s]

Device set to use cpu

In [ ]:
def transcribe_speech(filepath):
    output = pipe(
        filepath,
        max_new_tokens=256,
        chunk_length_s=30,
        batch_size=8,
    )
    return output["text"]

In [ ]:
# Start the timer
start_time = time.time()

# Initialize dictionary to store the predicted transcriptions
predicted_transcriptions = {}

# Loop over each .wav file in wav_files
for wav_file in wav_files:
    # Call the transcribe function to get the transcription for each wav file
    transcription = transcribe_speech(wav_file)

    # Get the file name (ID) from the full path
    wav_id = os.path.basename(wav_file)

    # Store the transcription in the dictionary
    predicted_transcriptions[wav_id] = transcription

# Stop the timer after processing all files
end_time = time.time()

/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(

In [ ]:
# Calculate total time taken in seconds
total_time = end_time - start_time

# Print the total time taken
print(f"Total time taken for transcription: {total_time:.2f} seconds")

Total time taken for transcription: 814.56 seconds

In [ ]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/FYP-Language_learning/transcriptions_comparison.csv")

In [ ]:
# Step 2: Create a new column 'transcription' based on the 'id' column matching dictionary keys
df['predicted_transcription_Whisper-small-en'] = df['id'].map(predicted_transcriptions)

df['predicted_transcription_Whisper-small-en'] = df['predicted_transcription_Whisper-small-en'].str.strip()

In [ ]:
# Helper function to check if a transcription contains digits
def contains_digits(text):
    return bool(re.search(r'\d', text))  # Returns True if there are any digits

# Initialize the normalizer
normalizer = BasicTextNormalizer()

# Dictionary to store normalized transcriptions without digits
normalized_dict = {}

# Filter and remove transcriptions with digits from the original dictionary
for audio_id, text in list(predicted_transcriptions.items()):  # Iterate through original dictionary
    if contains_digits(text):  # If transcription contains digits, remove from original dict
        del predicted_transcriptions[audio_id]  # Remove this entry from the original dictionary
        del orignal_transcriptions[audio_id]
    else:
        # Normalize the transcription if it does not contain digits
        normalized_text = normalizer(text.strip())
        normalized_dict[audio_id] = normalized_text  # Add to normalized dictionary

print("Length of normalized dict",len(normalized_dict))
print("Length of original dict",len(orignal_transcriptions))

Length of normalized dict 54
Length of original dict 54

In [ ]:
# from transformers.models.whisper.english_normalizer import BasicTextNormalizer

# normalizer = BasicTextNormalizer()

# # Apply the normalizer to each transcription in the dictionary
# normalized_dict = {audio_id: normalizer(text.strip()) for audio_id, text in predicted_transcriptions.items()}

# # Print the normalized transcriptions
print(normalized_dict)

{'G0007_0_S0020.wav': 'give up steps that hinder normal development in relations ', 'G0007_0_S0023.wav': 'the car s solar panel creates electricity from sunlight ', 'G0007_0_S0031.wav': 'the rebel was elvis presley the king of rock and roll ', 'G0007_0_S0024.wav': 'and its story of chief joseph of the naspers indians', 'G0007_0_S0040.wav': 'thanks for playing along i just have to sit for a while ', 'G0007_0_S0043.wav': 'one passenger died after being partially out of the plane ', 'G0007_0_S0018.wav': 'now now i have to go now i have to see the frozen charles now tonight ', 'G0007_0_S0042.wav': 'and she thanked the french people for sharing her despair ', 'G0008_0_S0049.wav': 'who do you think the wolves and the mavericks will take ', 'G0008_0_S0047.wav': 'and no it s not as if any of her already early stuff was less provocative ', 'G0008_0_S0016.wav': 'she looked down her nose at me and sneered ', 'G0008_0_S0043.wav': 'yes that s it i liked that one what about benny goodman you mentioned earlier ', 'G0008_0_S0025.wav': 'i didn t know it was an impulse me wearing my good shoes', 'G0008_0_S0023.wav': 'nox oh yes nox i m glad you called', 'G0008_0_S0017.wav': 'well we are starving why don t we all go to get something to eat ', 'G0008_0_S0028.wav': 'and the recommendation of their doctors are on their own ', 'G0008_0_S0048.wav': 'i like every sense equally they are all great ', 'G0009_0_S0039.wav': 'if you buy chicken at a good butcher s', 'G0009_0_S0032.wav': 'and there was the girl wearing that plain white dress and white cowboy boots ', 'G0009_0_S0042.wav': 'you want some breakfast meat michael is that what you want ', 'G0009_0_S0022.wav': 'the pictures showed what appeared to be high explosives in ', 'G0009_0_S0041.wav': 'much smaller than was done even at prudhoe bebok in the s ', 'G0009_0_S0015.wav': 'do not corrode and do not react with tin ', 'G0009_0_S0034.wav': 'oh okay had john kuzak in it i think ', 'G0009_0_S0030.wav': 'and second to enter the in the top spot', 'G0005_0_S0017.wav': 'i was just wondering if you happen to know anything about paul sheldon ', 'G0005_0_S0014.wav': 'it is a day to help the needy ', 'G0005_0_S0012.wav': 'and trash say bad things about your opponent', 'G0005_0_S0016.wav': 'wow i just ordered from amazon is this to be expected ', 'G0005_0_S0019.wav': 'think about what you are going to see and we are on thin ice ', 'G0006_0_S0021.wav': 'that was a great movie it was so funny ', 'G0006_0_S0011.wav': 'white flag of truce earlier in the day', 'G0006_0_S0023.wav': 'but what you said you only had sex with three guys you never mentioned him ', 'G0006_0_S0020.wav': 'having the new pipe solved a lot of problems ', 'G0006_0_S0024.wav': 'i actually haven t seen that one is it any good ', 'G0001_0_S0123.wav': 'i kind of thought it would be better than the second but it s really not ', 'G0001_0_S0124.wav': 'things begin to change in the late days ', 'G0001_0_S0102.wav': 'yeah he was everywhere then even my mom listened to him back then', 'G0001_0_S0119.wav': 'palestinians won their own state in all of the west ', 'G0001_0_S0132.wav': 'the curds reasserted their rice to the area after you ', 'G0001_0_S0109.wav': 'from that time until she was almost seven years old', 'G0001_0_S0114.wav': 'the demonstrators weave the lebanese flag at the sign of unity ', 'G0001_0_S0104.wav': 'she looks like the guy from why meets world with a wig on ', 'G0001_0_S0108.wav': 'we have to proceed and have to continue ', 'G0001_0_S0130.wav': 'come on man how on earth did you not see the sarcasm ', 'G0004_0_S0017.wav': 'who are you doctors adams was supposed to assist me ', 'G0004_0_S0029.wav': 'branch is the supreme court and the federal court system ', 'G0004_0_S0016.wav': 'there has to be more to be done', 'G0004_0_S0033.wav': 'no i get you i mean it s possible just keeping up with the big hollywood movies ', 'G0004_0_S0013.wav': 'it became an immediate best seller and remains popular today ', 'G0004_0_S0021.wav': 'do me a favor go back and quiet me from where i said apologize ', 'G0004_0_S0030.wav': 'not one inch should be gave to these people', 'G0004_0_S0037.wav': 'no i was hoping the colts would get to make a shot at him ', 'G0004_0_S0015.wav': 'caves are home to some of the strangest creatures on earth '}

In [ ]:
orignal_transcriptions

{'G0007_0_S0020.wav': 'give up steps that hinder normal development in relations',
 'G0007_0_S0023.wav': "the car's solar panel creates electricity from sunlight",
 'G0007_0_S0031.wav': 'the rebel was elvis presley the king of rock and roll',
 'G0007_0_S0024.wav': 'and its story of jeff joseph of the nez perce indians',
 'G0007_0_S0040.wav': 'thanks for playing along i just have to sit for a while',
 'G0007_0_S0043.wav': 'one passenger died after being partially out of the plane',
 'G0007_0_S0018.wav': 'now now i have to go now i have to see the frozen charles now tonight',
 'G0007_0_S0042.wav': 'and she thanked the french people for sharing her despair',
 'G0008_0_S0049.wav': 'who do you think the wolves and the mavericks will take',
 'G0008_0_S0047.wav': "i know it's not as if any of her really early stuff was less provocative",
 'G0008_0_S0016.wav': 'she looked down her nose at me and sneered',
 'G0008_0_S0043.wav': "yes that's it i liked that one what about benny goodman you mentioned earlier",
 'G0008_0_S0025.wav': 'i dunno it was an impulse me wearing my good shoes',
 'G0008_0_S0023.wav': "knox oh yes knox i'm glad you called",
 'G0008_0_S0017.wav': "well we're starving why don't we all go get something to eat",
 'G0008_0_S0028.wav': 'at the recommendation of their doctors or on their own',
 'G0008_0_S0048.wav': 'i like every scene equally they are all great',
 'G0009_0_S0039.wav': "if you buy chicken at a good butcher's",
 'G0009_0_S0032.wav': 'and there was the girl wearing that plain white dress and white cowboy boots',
 'G0009_0_S0042.wav': 'you want some breakfast meat micheal is that what you want',
 'G0009_0_S0022.wav': 'the pictures showed what appeared to be high exploses in',
 'G0009_0_S0041.wav': 'much smaller than was done\xa0even at  bay back in the s',
 'G0009_0_S0015.wav': 'do not corrode and do not react with tin',
 'G0009_0_S0034.wav': 'oh okay had john cusack in it i think',
 'G0009_0_S0030.wav': 'and second to enter the in the top spot',
 'G0005_0_S0017.wav': 'i was just wondering if you happen to know anything about paul sheldon',
 'G0005_0_S0014.wav': 'it is a day to help the needy',
 'G0005_0_S0012.wav': 'and try say bad things about your opponent',
 'G0005_0_S0016.wav': 'wow i just ordered from amzon is this to be expected',
 'G0005_0_S0019.wav': "think about what you're going to say add we are on thin ice",
 'G0006_0_S0021.wav': 'that was a great movie it was so funny',
 'G0006_0_S0011.wav': 'white flag of truce earlier in the day',
 'G0006_0_S0023.wav': 'but what you said you only had sex with three guys you never mentioned him',
 'G0006_0_S0020.wav': 'having the new pipes solved a lot of problems',
 'G0006_0_S0024.wav': "i actually haven't seen that one is it any good",
 'G0001_0_S0123.wav': "i kind of thought it would be better than the second, but it's really not.",
 'G0001_0_S0124.wav': 'things began to change in the late s.',
 'G0001_0_S0102.wav': 'yeah, he was everywhere then. even my mom listened to him back then.',
 'G0001_0_S0119.wav': 'palestinians want their own state in all of the west.',
 'G0001_0_S0132.wav': 'the kurds reasserted their rights to the area after u.',
 'G0001_0_S0109.wav': 'from that time until she was almost seven years old.',
 'G0001_0_S0114.wav': 'the demonstrators waved the lebanese flag as a sign of unity.',
 'G0001_0_S0104.wav': 'she looks like the guy from boy meets world with a wig on',
 'G0001_0_S0108.wav': 'we have to proceed and have to continue.',
 'G0001_0_S0130.wav': 'come on man how on earth did you not see the sarcasm',
 'G0004_0_S0017.wav': 'who are you doctor adams was supposed to assist me',
 'G0004_0_S0029.wav': 'branch is the supreme court and the federal court system',
 'G0004_0_S0016.wav': 'there has to be more to be done',
 'G0004_0_S0033.wav': "no i get you i mean it's impossible just keeping up with the big hollywood movies",
 'G0004_0_S0013.wav': 'it became an immediate best seller and remains popular today',
 'G0004_0_S0021.wav': 'do me a favour go back and quote me from where i said apologise',
 'G0004_0_S0030.wav': 'not one inch should we give to these people',
 'G0004_0_S0037.wav': 'no i was hoping the colts would get to make a shot at him',
 'G0004_0_S0015.wav': 'caves are home to some of the strangest creatures on earth'}

In [ ]:
# Initialize the WER metric
wer_metric = load("wer")

# Step 2: Calculate WER on the cleaned data
wer_ortho = 100 * wer_metric.compute(
    references=list(orignal_transcriptions.values()), predictions=list(normalized_dict.values()))

print(f"Word Error Rate (WER): {wer_ortho}%")

Word Error Rate (WER): 12.864493996569468%

**Whisper Base en**

In [ ]:
# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("automatic-speech-recognition", model="openai/whisper-base.en")

config.json:   0%|          | 0.00/1.94k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/290M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/1.53k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/805 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.41M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

normalizer.json:   0%|          | 0.00/52.7k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/1.83k [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/185k [00:00<?, ?B/s]

Device set to use cpu

In [ ]:
# Start the timer
start_time = time.time()

# Initialize dictionary to store the predicted transcriptions
predicted_transcriptions = {}

# Loop over each .wav file in wav_files
for wav_file in wav_files:
    # Call the transcribe function to get the transcription for each wav file
    transcription = transcribe_speech(wav_file)

    # Get the file name (ID) from the full path
    wav_id = os.path.basename(wav_file)

    # Store the transcription in the dictionary
    predicted_transcriptions[wav_id] = transcription

# Stop the timer after processing all files
end_time = time.time()

/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

In [ ]:
len(predicted_transcriptions)

140

In [ ]:
# Calculate total time taken in seconds
total_time = end_time - start_time

# Print the total time taken
print(f"Total time taken for transcription: {total_time:.2f} seconds")

Total time taken for transcription: 504.35 seconds

In [ ]:
# Step 2: Create a new column 'transcription' based on the 'id' column matching dictionary keys
df['predicted_transcription_Whisper-base-140-en'] = df['id'].map(predicted_transcriptions)

df['predicted_transcription_Whisper-base-140-en'] = df['predicted_transcription_Whisper-base-140-en'].str.strip()

In [ ]:
import re
from transformers.models.whisper.english_normalizer import BasicTextNormalizer

# Helper function to check if a transcription contains digits
def contains_digits(text):
    return bool(re.search(r'\d', text))  # Returns True if there are any digits

# Initialize the normalizer
normalizer = BasicTextNormalizer()

# Dictionary to store normalized transcriptions without digits
normalized_dict = {}

keys_to_remove = set(orignal_transcriptions.keys()) - set(predicted_transcriptions.keys())  # Find keys in original_dict but not in predicted_dict

# Remove those keys from original_dict
for key in keys_to_remove:
    del orignal_transcriptions[key]

# Filter and remove transcriptions with digits from the original dictionary
for audio_id, text in list(predicted_transcriptions.items()):  # Iterate through original dictionary
    if contains_digits(text):  # If transcription contains digits, remove from original dict
        del predicted_transcriptions[audio_id]  # Remove this entry from the original dictionary
        del orignal_transcriptions[audio_id]
    else:
        # Normalize the transcription if it does not contain digits
        normalized_text = normalizer(text.strip())
        normalized_dict[audio_id] = normalized_text  # Add to normalized dictionary

print("Length of normalized dict",len(normalized_dict))
print("Length of original dict",len(orignal_transcriptions))

Length of normalized dict 99
Length of original dict 99

In [ ]:
print(normalized_dict)
print(orignal_transcriptions)

{'G0007_0_S0020.wav': 'give up steps that hinder normal development in relations ', 'G0007_0_S0023.wav': 'the car s solar panel creates electricity from sunlight ', 'G0007_0_S0031.wav': 'the rebel was always personally the king of rock and roll ', 'G0007_0_S0024.wav': 'and its story of chief joseph of the naspers indians ', 'G0007_0_S0040.wav': 'thanks for playing along i just have to sit for a while ', 'G0007_0_S0043.wav': 'one person s here tight after being partially out of the plane ', 'G0007_0_S0018.wav': 'now now i have to go now i have to see the frozen charles now tonight ', 'G0007_0_S0042.wav': 'and she thanked the french people for sharing her despair ', 'G0008_0_S0049.wav': 'who do you think the walls and the mavericks will take ', 'G0008_0_S0047.wav': 'and now it s not as if any of her really early stuff was less provocative ', 'G0008_0_S0016.wav': 'she looked down her nose at me and sneered ', 'G0008_0_S0043.wav': 'yes that s it i like that one what about benny goodman you mentioned earlier ', 'G0008_0_S0025.wav': 'i didn t know it was an impulse me wearing my good shoes ', 'G0008_0_S0023.wav': 'knox yes knox i am glad you called ', 'G0008_0_S0017.wav': 'well we are starving why don t we all go to get something to eat ', 'G0008_0_S0028.wav': 'as the recommendation of their doctors are on their own', 'G0008_0_S0048.wav': 'i like every sense equally they are all great ', 'G0009_0_S0039.wav': 'if you buy chicken at a good butcher s', 'G0009_0_S0032.wav': 'and there was the goal wearing that plain white dress and white cowboy boots ', 'G0009_0_S0042.wav': 'you want some breakfast meat michael is that what you want ', 'G0009_0_S0022.wav': 'the pictures showed what appeared to be high explosives in ', 'G0009_0_S0041.wav': 'much smaller than was done even at prudhoe baybogg in the s ', 'G0009_0_S0034.wav': 'oh okay had john q zack in it i think ', 'G0009_0_S0030.wav': 'and second to enter the in the top spot ', 'G0005_0_S0017.wav': 'i was just wondering if you happen to know anything about ball children ', 'G0005_0_S0014.wav': 'it is a day to help the needy ', 'G0005_0_S0012.wav': 'and trash the bad things about your opponent', 'G0005_0_S0016.wav': 'wow i just ordered from amazon is this to be expected ', 'G0005_0_S0019.wav': 'think about what you are going to see and we are on thin eyes ', 'G0006_0_S0021.wav': 'that was a great movie it was so funny ', 'G0006_0_S0011.wav': 'white flag of truth earlier in the day ', 'G0006_0_S0023.wav': 'but you said you only had sex with three guys you never mentioned him ', 'G0006_0_S0020.wav': 'having the new pipes solved a lot of problems ', 'G0006_0_S0024.wav': 'i actually haven t seen that one is it any good ', 'G0001_0_S0123.wav': 'i kind of thought it would be better than the second but it s very not ', 'G0001_0_S0124.wav': 'things begin to change in the lead as', 'G0001_0_S0102.wav': 'yeah he was everywhere then even my mom listened to him back then ', 'G0001_0_S0119.wav': 'palestinians want their own state in all of the west ', 'G0001_0_S0132.wav': 'the curse reasserted their rise to the ad after you ', 'G0001_0_S0114.wav': 'did you monstrator sweep the lebanese flag at the sign of unity ', 'G0001_0_S0104.wav': 'she looks like the guy from y meets world with a wig on ', 'G0001_0_S0108.wav': 'we have to proceed and have to continue ', 'G0001_0_S0130.wav': 'come on man how on earth did you not see the sarcasm ', 'G0004_0_S0017.wav': 'who are you doctors adams are supposed to assist me ', 'G0004_0_S0029.wav': 'branch is the supreme court and the federal court system ', 'G0004_0_S0016.wav': 'there has to be more to be done ', 'G0004_0_S0033.wav': 'no i get you i mean it s possible just keeping up with the big hollywood movies ', 'G0004_0_S0013.wav': 'it became an immediate best sailor and remains popular today ', 'G0004_0_S0021.wav': 'do me a favor go back and quiet me from where i said apologize ', 'G0004_0_S0037.wav': 'no i was hoping the colts would get to make a shot at him ', 'G0004_0_S0015.wav': 'caves are home to some of the such ranges to create shares on earth '}
{'G0007_0_S0020.wav': 'give up steps that hinder normal development in relations', 'G0007_0_S0023.wav': "the car's solar panel creates electricity from sunlight", 'G0007_0_S0031.wav': 'the rebel was elvis presley the king of rock and roll', 'G0007_0_S0024.wav': 'and its story of jeff joseph of the nez perce indians', 'G0007_0_S0040.wav': 'thanks for playing along i just have to sit for a while', 'G0007_0_S0043.wav': 'one passenger died after being partially out of the plane', 'G0007_0_S0018.wav': 'now now i have to go now i have to see the frozen charles now tonight', 'G0007_0_S0042.wav': 'and she thanked the french people for sharing her despair', 'G0008_0_S0049.wav': 'who do you think the wolves and the mavericks will take', 'G0008_0_S0047.wav': "i know it's not as if any of her really early stuff was less provocative", 'G0008_0_S0016.wav': 'she looked down her nose at me and sneered', 'G0008_0_S0043.wav': "yes that's it i liked that one what about benny goodman you mentioned earlier", 'G0008_0_S0025.wav': 'i dunno it was an impulse me wearing my good shoes', 'G0008_0_S0023.wav': "knox oh yes knox i'm glad you called", 'G0008_0_S0017.wav': "well we're starving why don't we all go get something to eat", 'G0008_0_S0028.wav': 'at the recommendation of their doctors or on their own', 'G0008_0_S0048.wav': 'i like every scene equally they are all great', 'G0009_0_S0039.wav': "if you buy chicken at a good butcher's", 'G0009_0_S0032.wav': 'and there was the girl wearing that plain white dress and white cowboy boots', 'G0009_0_S0042.wav': 'you want some breakfast meat micheal is that what you want', 'G0009_0_S0022.wav': 'the pictures showed what appeared to be high exploses in', 'G0009_0_S0041.wav': 'much smaller than was done\xa0even at  bay back in the s', 'G0009_0_S0034.wav': 'oh okay had john cusack in it i think', 'G0009_0_S0030.wav': 'and second to enter the in the top spot', 'G0005_0_S0017.wav': 'i was just wondering if you happen to know anything about paul sheldon', 'G0005_0_S0014.wav': 'it is a day to help the needy', 'G0005_0_S0012.wav': 'and try say bad things about your opponent', 'G0005_0_S0016.wav': 'wow i just ordered from amzon is this to be expected', 'G0005_0_S0019.wav': "think about what you're going to say add we are on thin ice", 'G0006_0_S0021.wav': 'that was a great movie it was so funny', 'G0006_0_S0011.wav': 'white flag of truce earlier in the day', 'G0006_0_S0023.wav': 'but what you said you only had sex with three guys you never mentioned him', 'G0006_0_S0020.wav': 'having the new pipes solved a lot of problems', 'G0006_0_S0024.wav': "i actually haven't seen that one is it any good", 'G0001_0_S0123.wav': "i kind of thought it would be better than the second, but it's really not.", 'G0001_0_S0124.wav': 'things began to change in the late s.', 'G0001_0_S0102.wav': 'yeah, he was everywhere then. even my mom listened to him back then.', 'G0001_0_S0119.wav': 'palestinians want their own state in all of the west.', 'G0001_0_S0132.wav': 'the kurds reasserted their rights to the area after u.', 'G0001_0_S0114.wav': 'the demonstrators waved the lebanese flag as a sign of unity.', 'G0001_0_S0104.wav': 'she looks like the guy from boy meets world with a wig on', 'G0001_0_S0108.wav': 'we have to proceed and have to continue.', 'G0001_0_S0130.wav': 'come on man how on earth did you not see the sarcasm', 'G0004_0_S0017.wav': 'who are you doctor adams was supposed to assist me', 'G0004_0_S0029.wav': 'branch is the supreme court and the federal court system', 'G0004_0_S0016.wav': 'there has to be more to be done', 'G0004_0_S0033.wav': "no i get you i mean it's impossible just keeping up with the big hollywood movies", 'G0004_0_S0013.wav': 'it became an immediate best seller and remains popular today', 'G0004_0_S0021.wav': 'do me a favour go back and quote me from where i said apologise', 'G0004_0_S0037.wav': 'no i was hoping the colts would get to make a shot at him', 'G0004_0_S0015.wav': 'caves are home to some of the strangest creatures on earth'}

In [ ]:
import re
from evaluate import load

# Initialize the WER metric
wer_metric = load("wer")

# Step 2: Calculate WER on the cleaned data
wer_ortho = 100 * wer_metric.compute(
    references=list(orignal_transcriptions.values()), predictions=list(normalized_dict.values()))

print(f"Word Error Rate (WER): {wer_ortho}%")

Word Error Rate (WER): 17.11378353376503%

**Whisper distil Medium en**

In [ ]:
# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("automatic-speech-recognition", model="openai/whisper-medium.en")

config.json:   0%|          | 0.00/1.95k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/3.06G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/1.95k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/805 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.41M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

normalizer.json:   0%|          | 0.00/52.7k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/1.83k [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/185k [00:00<?, ?B/s]

Device set to use cpu

In [ ]:
# Start the timer
start_time = time.time()

# Initialize dictionary to store the predicted transcriptions
predicted_transcriptions = {}

# Loop over each .wav file in wav_files
for wav_file in wav_files:
    # Call the transcribe function to get the transcription for each wav file
    transcription = transcribe_speech(wav_file)

    # Get the file name (ID) from the full path
    wav_id = os.path.basename(wav_file)

    # Store the transcription in the dictionary
    predicted_transcriptions[wav_id] = transcription

# Stop the timer after processing all files
end_time = time.time()

/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/automatic_speech_recognition.py:312: FutureWarning: `max_new_tokens` is deprecated and will be removed in version 4.49 of Transformers. To remove this warning, pass `max_new_tokens` as a key inside `generate_kwargs` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/transformers/models/whisper/generation_whisper.py:512: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(

In [ ]:
# Calculate total time taken in seconds
total_time = end_time - start_time

# Print the total time taken
print(f"Total time taken for transcription: {total_time:.2f} seconds")

Total time taken for transcription: 2347.68 seconds

In [ ]:
# Step 2: Create a new column 'transcription' based on the 'id' column matching dictionary keys
df['predicted_transcription_Whisper-distill-medium-en'] = df['id'].map(predicted_transcriptions)

df['predicted_transcription_Whisper-distill-medium-en'] = df['predicted_transcription_Whisper-distill-medium-en'].str.strip()

In [ ]:
import re
from transformers.models.whisper.english_normalizer import BasicTextNormalizer

# Helper function to check if a transcription contains digits
def contains_digits(text):
    return bool(re.search(r'\d', text))  # Returns True if there are any digits

# Initialize the normalizer
normalizer = BasicTextNormalizer()

# Dictionary to store normalized transcriptions without digits
normalized_dict = {}

keys_to_remove = set(orignal_transcriptions.keys()) - set(predicted_transcriptions.keys())  # Find keys in original_dict but not in predicted_dict

# Remove those keys from original_dict
for key in keys_to_remove:
    del orignal_transcriptions[key]

# Filter and remove transcriptions with digits from the original dictionary
for audio_id, text in list(predicted_transcriptions.items()):  # Iterate through original dictionary
    if contains_digits(text):  # If transcription contains digits, remove from original dict
        del predicted_transcriptions[audio_id]  # Remove this entry from the original dictionary
        del orignal_transcriptions[audio_id]
    else:
        # Normalize the transcription if it does not contain digits
        normalized_text = normalizer(text.strip())
        normalized_dict[audio_id] = normalized_text  # Add to normalized dictionary

print("Length of normalized dict",len(normalized_dict))
print("Length of original dict",len(orignal_transcriptions))

Length of normalized dict 53
Length of original dict 53

In [ ]:
import re
from evaluate import load

# Initialize the WER metric
wer_metric = load("wer")

# Step 2: Calculate WER on the cleaned data
wer_ortho = 100 * wer_metric.compute(
    references=list(orignal_transcriptions.values()), predictions=list(normalized_dict.values()))

print(f"Word Error Rate (WER): {wer_ortho}%")

Word Error Rate (WER): 12.390924956369982%